config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  get :user_badges, to: 'badges#gained_badges'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges, except: :show
  end
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'

  has_many :user_badges
  has_many :users, through: :user_badges, dependent: :destroy

  validates :title, presence: true
  validates :image_url, presence: true
  validates :description, presence: true
  validates :criteria, presence: true, uniqueness: { scope: :criteria_value }

  def self.criteria
    {
      "Успешное прохождение всех тестов из категории": :passed_all_tests_for_category,
      "Успешное прохождение теста с попытки №": :test_passed_by_try,
      "Успешное прохождение всех тестов уровня": :passed_all_tests_for_level
    }
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[destroy edit update]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = current_user.created_badges.build(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image_url, :description, :criteria, :criteria_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end

  def gained_badges
    @badges = current_user.badges
    render :index
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.title %></td>
  <td class="align-middle">
    <%= image_tag badge.image_url, class: 'badge-image' do %>
    <% end %>
  </td>
  <td class="align-middle"><%= badge.description %></td>
  <td class="align-middle"><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to 'Delete', admin_badge_path(badge), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :badge_title %>
  </div>

  <div>
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url, id: :badge_image_url %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description, id: :badge_description %>
  </div>

  <div>
    <%= form.label :criteria %><br>
    <%= form.select :criteria, Badge.criteria.to_a %>
  </div>

  <div>
    <%= form.label :criteria_value %><br>
    <%= form.text_field :criteria_value, id: :badge_criteria_value %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit "<%= @badge.title %>" Badge</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back to all badges', admin_badges_path %>
</p>

app/views/admin/badges/index.html.erb
<h1> All Badges </h1>

<p>
  <%= link_to 'New Badge', new_admin_badge_path %> 
</p>

<%= render 'shared/errors', resource: @badge %>

<table class="table">
  <thead>
    <tr>
      <th>Badge Title</th>
      <th>Badge Image</th>
      <th>Description</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @badges %>
  </tbody>
</table>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back to all badges', admin_badges_path %>
</p>