config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  get :user_badges, to: 'badges#gained_badges'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS_RATIO = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    self.successful = success?
    save!
  end

  def completed?
    current_question.nil? || time_is_over?
  end

  def total
    test.questions.count
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def score
    self.correct_questions
  end

  def percent
    (score.to_f / total * 100).round(2)
  end

  def success?
    percent >= SUCCESS_RATIO && !time_is_over?
  end

  def end_time
    test_time = self.test.time_limit
    created_at + test_time.hour.hours + test_time.min.minutes + test_time.sec.seconds
  end

  def time_is_over?
    Time.now >= end_time - 1.seconds
  end

  private

  def before_validation_set_current_question
    self.current_question = next_question
  end

  def next_question
    current_question ? test.questions.order(:id).where('id > ?', current_question.id).first : test.questions.first
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answers
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  rescue_from NoMethodError, with: :rescue_with_no_questions

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      GiveBadgesService.new(@test_passage).call
      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end

  def rescue_with_no_questions
    flash[:alert] = 'No questions for this test'
    redirect_to tests_path
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def result_class(test_passage)
    test_passage.success? ? 'success-message' : 'fail-message'
  end

  def result_message(test_passage)
    test_passage.success? ? 'Test is passed' : 'Test is not passed'
  end
end

app/views/test_passages/result.html.erb
<h1>The <%= @test_passage.test.title %> Test was Comleted </h1>

<p class=" <%= result_class(@test_passage) %> ">
  Your result: <%= @test_passage.score %> of <%= @test_passage.total %> (<%= @test_passage.percent %>%)<br>
  <%= result_message(@test_passage) %>
</p>

<p>
  <%= link_to 'Back to all tests', tests_path %>
</p>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<%= content_tag :p,
                class: 'timer',
                data: { end_time: @test_passage.end_time.to_s } do %>
<% end %>

<%= content_tag :progress, 
                class: 'progress-line', 
                data: { current_question_number: @test_passage.current_question_number, total: @test_passage.total } do %>
<% end %>

<b>
  <%= @test_passage.current_question_number %>/<%= @test_passage.total %>
  <%= @test_passage.current_question.title %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :title, include_hidden: false do |b| %>
    <div>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </div>
  <% end %>

  <div>
    <%= link_to 'Gist Question', test_passage_gists_path(@test_passage), method: :post %><br>
    <%= form.submit 'Next', class: 'next-button' %>
  </div>
<% end %>