config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  get :user_badges, to: 'badges#gained_badges'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges, except: :show
  end
end

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>

  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected: </h2>

    <ul>
      <% resource.errors.each do |message| %>
          <li><%= message.full_message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= flash_message(key) %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>Текущий год: <%= current_year %></p>
  <p>Имя автора: Софья Попова</p>
  <p>Проект <%= github_url(author: 'alexsp63', repo: 'TestGuru') %></p>
  <p>Онлайн-школа <%= link_to "Thinknetica", "http://thinknetica.com/", target: "_blank", rel: "nofollow" %></p>
</footer>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <ul class="nav-ul">
    <li class="nav-li"><p>Welcome, <b><%= current_user.username %></b> Guru </p></li>
    <li class="nav-li"><%= link_to 'TestGuru', tests_path %></li>
    <li class="nav-li"><%= link_to 'Badges List', badges_path %></li>
    <li class="nav-li"><%= link_to 'My Badges', user_badges_path %></li>
    <li class="nav-li"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
  </ul>
  <% else %>
    <ul class="nav-ul">
      <li class="nav-li"><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li class="nav-li"><%= link_to 'Log In', new_user_session_path %></li>
    </ul>
<% end %>