config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'tests#index'

  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badges, only: :index

  get :user_badges, to: 'badges#gained_badges'

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: :create
  end

  namespace :admin do
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
    resources :badges, except: :show
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[show destroy edit update]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = @test.questions.build(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def rescue_with_question_not_found
    render plain: 'No question found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question, test)
    if question.persisted?
      "Edit #{test.title.titleize} Question"
    else
      "Create New #{test.title.titleize} Question"
    end
  end

  def questions_number(test)
    test.questions.count
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :question_title %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.title %></td>
  <td><%= link_to 'Show', admin_question_path(question) %></td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %></td>
  <td><%= link_to 'Delete', admin_question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question, @question.test) %></h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back to all questions', admin_test_path(@question.test) %> |
  <%= link_to 'Delete', admin_test_path(@question.test), method: :delete, data: { confirm: 'Are you sure?' } %> 
</p>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question, @test) %></h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back to all questions', admin_test_path(@test) %>
</p>

app/views/admin/questions/show.html.erb
<h1>Question <%= @question.id %> </h1>

<p> Question text: <%= @question.title %> </p><br>

<h2>Question Answers</h2>

<%= link_to 'New answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<p>
  <%= link_to 'Back to all questions', admin_test_path(@question.test) %> |
  <%= link_to 'Edit', edit_admin_question_path(@question) %> |
  <%= link_to 'Delete', admin_question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>